### ISSUE TITLE
annotation files

### ISSUE THREAD

**Issue by Jinjie-Duan** [andgan/ultra_rare_pheno_spectrum#1]
Hi Andrea,

Thanks for your shared code and resources. It's really a huge help for hail beginner. I am following your annotation code and wondering if you could also share the other two annotation files, named as
dbNSFP_3.2a_variant.filtered.allhg19_nodup.vds & fordist_constraint_official_mpc_values.txt.gz. Many thanks in advance.

cheers,
Jinjie

**Comment by Jinjie-Duan** [comment]
I just realized the original dbNSFP is quite big, so I just downloaded from their webpage directly. Did you do any filtering or other stuff to generate dbNSFP_3.2a_variant.filtered.allhg19_nodup.vds?

**Comment by andgan** [comment]
Hi, sorry for the late reply, somehow I didn't receive notifications. No filter that I remember, probably removed duplicated SNPs.
